blank_issues_enabled: false
contact_links:
  - name: Feature requests
    url: https://discuss.bitrise.io/
    about: Please raise feature requests here.
  - name: Questions
    url: https://discuss.bitrise.io/
    about: Please aks any questions here.
