blank_issues_enabled: false
contact_links:
  - name: 🚀 Feature requests
    url: https://discuss.bitrise.io/
    about: Share new feature ideas
  - name: ❓ Ask a question
    url: https://discuss.bitrise.io/
    about: Ask any question you have
